// frontend-angular/src/app/components/on-tick-form/on-tick-form.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-on-tick-form',
  templateUrl: './on-tick-form.component.html',
  styleUrls: ['./on-tick-form.component.scss']
})
export class OnTickFormComponent {
  @Input() sessionId: string = '';
  @Input() organizationId: string = '';
  @Input() userId: string = '';
  
  @Output() sessionCreated = new EventEmitter<string>();
  @Output() errorOccurred = new EventEmitter<string>();

  form: FormGroup;
  isSubmitting = false;
  responseMessage = '';
  responseType: 'success' | 'error' | null = null;

  constructor(
    private fb: FormBuilder,
    private http: HttpClient
  ) {
    this.form = this.fb.group({
      prompt: ['', [Validators.required, Validators.minLength(3)]],
      sessionId: [this.sessionId || 'test-session-' + Date.now(), Validators.required],
      organizationId: [this.organizationId || 'org-pablo-astrologia', Validators.required],
      userId: [this.userId || 'pablo-admin', Validators.required]
    });
  }

  ngOnChanges() {
    // Update form values when inputs change
    if (this.sessionId) {
      this.form.patchValue({ sessionId: this.sessionId });
    }
    if (this.organizationId) {
      this.form.patchValue({ organizationId: this.organizationId });
    }
    if (this.userId) {
      this.form.patchValue({ userId: this.userId });
    }
  }

  onSubmit() {
    if (this.form.invalid) {
      this.markFormGroupTouched(this.form);
      return;
    }

    this.isSubmitting = true;
    this.responseMessage = '';
    this.responseType = null;

    const formData = this.form.value;
    
    // Cloud Function URL - should be in environment
    const cloudFunctionUrl = 'https://us-central1-hub-kraken-ia.cloudfunctions.net/onTick';

    this.http.post(cloudFunctionUrl, formData).subscribe({
      next: (response: any) => {
        this.isSubmitting = false;
        this.responseType = 'success';
        this.responseMessage = `✅ Session "${formData.sessionId}" created successfully!`;
        
        // Emit the session ID for parent component
        this.sessionCreated.emit(formData.sessionId);
        
        // Reset form but keep IDs
        this.form.patchValue({
          prompt: '',
          sessionId: formData.sessionId,
          organizationId: formData.organizationId,
          userId: formData.userId
        });
      },
      error: (error) => {
        this.isSubmitting = false;
        this.responseType = 'error';
        
        if (error.status === 0) {
          this.responseMessage = '❌ Network error: Could not reach the server. Check your connection.';
        } else if (error.status === 404) {
          this.responseMessage = '❌ Cloud Function not found. Make sure it\'s deployed.';
        } else if (error.status === 500) {
          this.responseMessage = '❌ Server error: Something went wrong on the server.';
        } else {
          this.responseMessage = `❌ Error: ${error.message || 'Unknown error occurred'}`;
        }
        
        this.errorOccurred.emit(this.responseMessage);
      }
    });
  }

  private markFormGroupTouched(formGroup: FormGroup) {
    Object.values(formGroup.controls).forEach(control => {
      control.markAsTouched();

      if (control instanceof FormGroup) {
        this.markFormGroupTouched(control);
      }
    });
  }

  get prompt() {
    return this.form.get('prompt');
  }

  get sessionIdControl() {
    return this.form.get('sessionId');
  }

  get organizationIdControl() {
    return this.form.get('organizationId');
  }

  get userIdControl() {
    return this.form.get('userId');
  }
}
<div class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6 shadow-lg">
  <h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-6">
    Create New Kraken Session
  </h2>

  <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-6">
    <!-- Prompt Input -->
    <div>
      <label for="prompt" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
        Your Prompt to Kraken *
      </label>
      <textarea
        id="prompt"
        formControlName="prompt"
        rows="4"
        class="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
        placeholder="Ask Kraken anything... e.g., 'Kraken, reporte seu status operacional agora.'"
      ></textarea>
      
      <div *ngIf="prompt?.invalid && (prompt?.touched || prompt?.dirty)" class="mt-2 text-sm text-red-600">
        <div *ngIf="prompt?.errors?.['required']">Prompt is required</div>
        <div *ngIf="prompt?.errors?.['minlength']">Prompt must be at least 3 characters</div>
      </div>
    </div>

    <!-- Session ID -->
    <div>
      <label for="sessionId" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
        Session ID *
      </label>
      <input
        type="text"
        id="sessionId"
        formControlName="sessionId"
        class="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
        placeholder="e.g., test-session-001"
      >
      <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
        Unique identifier for this session. Leave as-is for testing.
      </p>
    </div>

    <!-- Organization ID -->
    <div>
      <label for="organizationId" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
        Organization ID *
      </label>
      <input
        type="text"
        id="organizationId"
        formControlName="organizationId"
        class="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
        placeholder="e.g., org-pablo-astrologia"
      >
    </div>

    <!-- User ID -->
    <div>
      <label for="userId" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
        User ID *
      </label>
      <input
        type="text"
        id="userId"
        formControlName="userId"
        class="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
        placeholder="e.g., pablo-admin"
      >
    </div>

    <!-- Response Message -->
    <div *ngIf="responseMessage" class="p-4 rounded-lg" [ngClass]="{
      'bg-green-50 border border-green-200 text-green-800': responseType === 'success',
      'bg-red-50 border border-red-200 text-red-800': responseType === 'error'
    }">
      <div class="flex items-start">
        <div class="flex-shrink-0">
          <span *ngIf="responseType === 'success'" class="text-green-600">✅</span>
          <span *ngIf="responseType === 'error'" class="text-red-600">❌</span>
        </div>
        <div class="ml-3">
          <p class="text-sm font-medium">{{ responseMessage }}</p>
        </div>
      </div>
    </div>

    <!-- Submit Button -->
    <div class="flex items-center justify-between pt-4">
      <div class="text-sm text-gray-500 dark:text-gray-400">
        <p>This will trigger the Kraken Cloud Function and create a new session in Firestore.</p>
      </div>
      
      <button
        type="submit"
        [disabled]="isSubmitting || form.invalid"
        class="px-6 py-3 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white font-semibold rounded-lg shadow-md transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
      >
        <span *ngIf="isSubmitting" class="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full"></span>
        {{ isSubmitting ? 'Creating Session...' : 'Create Session' }}
      </button>
    </div>
  </form>

  <!-- Help Text -->
  <div class="mt-8 pt-6 border-t border-gray-200 dark:border-gray-700">
    <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-3">How it works:</h3>
    <ul class="space-y-2 text-sm text-gray-600 dark:text-gray-400">
      <li class="flex items-start gap-2">
        <span class="text-blue-500">1.</span>
        <span>Enter your prompt and session details above</span>
      </li>
      <li class="flex items-start gap-2">
        <span class="text-blue-500">2.</span>
        <span>Click "Create Session" to trigger the Kraken Cloud Function</span>
      </li>
      <li class="flex items-start gap-2">
        <span class="text-blue-500">3.</span>
        <span>The function will process your request and stream responses to Firestore</span>
      </li>
      <li class="flex items-start gap-2">
        <span class="text-blue-500">4.</span>
        <span>Watch the Session Viewer below for real-time updates</span>
      </li>
    </ul>
  </div>
</div>

// frontend/components/OnTickForm.tsx
'use client';

import { useState } from 'react';

interface OnTickFormProps {
  sessionId: string;
  organizationId: string;
  userId: string;
  onSuccess?: () => void;
}

export default function OnTickForm({
  sessionId,
  organizationId,
  userId,
  onSuccess,
}: OnTickFormProps) {
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim()) return;

    setLoading(true);
    setError(null);
    setSuccess(false);

    try {
      // Obter URL da Cloud Function
      const functionUrl = process.env.NEXT_PUBLIC_CLOUD_FUNCTION_URL || 
        `https://${process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || 'your-project'}-us-central1.cloudfunctions.net/onTick`;

      const response = await fetch(functionUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          sessionId,
          prompt: prompt.trim(),
          organizationId,
          userId,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to process request');
      }

      const data = await response.json();
      setSuccess(true);
      setPrompt('');
      
      if (onSuccess) {
        onSuccess();
      }

      // Reset success message after 3 seconds
      setTimeout(() => setSuccess(false), 3000);
    } catch (err: any) {
      setError(err.message || 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="w-full max-w-4xl mx-auto p-4 space-y-4">
      <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-4">
        <label htmlFor="prompt" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
          Enter your prompt:
        </label>
        <textarea
          id="prompt"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Type your message here..."
          className="w-full min-h-[120px] p-3 border border-gray-300 dark:border-gray-600 rounded-lg 
                     bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100
                     focus:ring-2 focus:ring-blue-500 focus:border-transparent
                     resize-y"
          disabled={loading}
        />
        
        {error && (
          <div className="mt-2 p-2 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded text-red-800 dark:text-red-200 text-sm">
            {error}
          </div>
        )}

        {success && (
          <div className="mt-2 p-2 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded text-green-800 dark:text-green-200 text-sm">
            Request sent successfully! Check the session viewer for streaming updates.
          </div>
        )}

        <button
          type="submit"
          disabled={loading || !prompt.trim()}
          className="mt-4 w-full sm:w-auto px-6 py-2 bg-blue-600 hover:bg-blue-700 
                     disabled:bg-gray-400 disabled:cursor-not-allowed
                     text-white font-semibold rounded-lg transition-colors"
        >
          {loading ? (
            <span className="flex items-center justify-center gap-2">
              <span className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></span>
              Processing...
            </span>
          ) : (
            'Send Prompt'
          )}
        </button>
      </div>
    </form>
  );
}
