// frontend-angular/src/app/components/session-viewer/session-viewer.component.ts
import { Component, Input, OnInit, OnDestroy, ChangeDetectionStrategy, ElementRef, ViewChild, AfterViewChecked } from '@angular/core';
import { Observable, Subscription, combineLatest, BehaviorSubject } from 'rxjs';
import { map, distinctUntilChanged, tap, switchMap } from 'rxjs/operators';
import { FirebaseService } from '@services/firebase.service';
import { SessionData, SessionViewerProps } from '@models/session.model';
import { environment } from '@environments/environment';

@Component({
  selector: 'app-session-viewer',
  templateUrl: './session-viewer.component.html',
  styleUrls: ['./session-viewer.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SessionViewerComponent implements OnInit, OnDestroy, AfterViewChecked {
  @Input() sessionId: string = environment.defaultSessionId;
  @Input() organizationId: string = environment.defaultOrganizationId;
  @Input() typewriterSpeed: number = environment.typewriterSpeed;

  @ViewChild('deltaContainer') deltaContainer!: ElementRef<HTMLDivElement>;
  @ViewChild('accumulatedContainer') accumulatedContainer!: ElementRef<HTMLDivElement>;

  // Observables
  sessionData$!: Observable<SessionData | null>;
  typewriterText$!: Observable<string>;
  isTyping$ = new BehaviorSubject<boolean>(false);
  
  // State
  accumulatedText = '';
  loading = true;
  error: string | null = null;
  lastDeltaKey = 0;
  isUserScrolledUp = false;

  // Subscriptions
  private subscriptions: Subscription[] = [];

  constructor(private firebaseService: FirebaseService) {}

  ngOnInit(): void {
    this.setupObservables();
    this.setupSubscriptions();
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }

  ngAfterViewChecked(): void {
    this.handleAutoScroll();
  }

  private setupObservables(): void {
    // Observable para dados da sessão
    this.sessionData$ = this.firebaseService.listenToSession(this.sessionId).pipe(
      tap(sessionData => {
        if (sessionData) {
          this.loading = false;
          this.error = null;
          
          // Validação de organização
          if (!this.firebaseService.validateSessionOrganization(sessionData, this.organizationId)) {
            this.error = `Session does not belong to organization: ${this.organizationId}`;
            return;
          }

          // Acumular texto
          if (sessionData.lastDelta) {
            this.accumulateText(sessionData.lastDelta);
            this.lastDeltaKey++;
          }
        } else {
          this.error = `Session "${this.sessionId}" not found in Firestore`;
          this.loading = false;
        }
      }),
      distinctUntilChanged((prev, curr) => 
        prev?.lastDelta === curr?.lastDelta && 
        prev?.status === curr?.status
      )
    );

  // Observable para efeito typewriter
  this.typewriterText$ = this.sessionData$.pipe(
    map(sessionData => sessionData?.lastDelta || ''),
    distinctUntilChanged(),
    tap(lastDelta => {
      if (lastDelta) {
        this.isTyping$.next(true);
      }
    }),
    switchMap(lastDelta => this.firebaseService.createTypewriterStream(lastDelta, this.typewriterSpeed)),
    tap({
      complete: () => this.isTyping$.next(false)
    })
  );
  }

  private setupSubscriptions(): void {
    // Subscription para typewriter
    const typewriterSub = this.typewriterText$.subscribe();
    this.subscriptions.push(typewriterSub);

    // Subscription para scroll automático
    const scrollSub = this.isTyping$.subscribe(isTyping => {
      if (isTyping && this.deltaContainer) {
        this.firebaseService.scrollToBottom(this.deltaContainer.nativeElement);
      }
    });
    this.subscriptions.push(scrollSub);
  }

  private accumulateText(newDelta: string): void {
    // Verifica se o final do texto acumulado já contém o delta para evitar duplicidade
    if (!this.accumulatedText.endsWith(newDelta)) {
      this.accumulatedText += newDelta;
    }
  }

  private handleAutoScroll(): void {
    if (this.accumulatedContainer && !this.isUserScrolledUp) {
      const container = this.accumulatedContainer.nativeElement;
      if (this.firebaseService.isAtBottom(container)) {
        this.firebaseService.scrollToBottom(container);
      }
    }
  }

  onScroll(event: Event): void {
    const container = event.target as HTMLDivElement;
    this.isUserScrolledUp = !this.firebaseService.isAtBottom(container);
  }

  getStatusColorClass(status: string): string {
    return this.firebaseService.getStatusColorClass(status);
  }

  formatTimestamp(timestamp: any): string {
    return this.firebaseService.formatTimestamp(timestamp);
  }

  // Template helpers
  get isLoading(): boolean {
    return this.loading;
  }

  get hasError(): boolean {
    return this.error !== null;
  }

  get errorMessage(): string {
    return this.error || '';
  }

  get sessionInfo(): { sessionId: string, organizationId: string } {
    return {
      sessionId: this.sessionId,
      organizationId: this.organizationId
    };
  }
}
<div *ngIf="isLoading" class="flex flex-col items-center justify-center p-8 space-y-4">
  <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
  <p class="text-gray-600 dark:text-gray-400">
    Listening to session: <span class="font-mono font-bold">{{ sessionId }}</span>
  </p>
</div>

<div *ngIf="hasError" class="bg-red-50 border border-red-200 rounded-lg p-6">
  <div class="flex items-start gap-3">
    <div class="flex-shrink-0">
      <div class="h-8 w-8 rounded-full bg-red-100 flex items-center justify-center">
        <span class="text-red-600 font-bold">!</span>
      </div>
    </div>
    <div>
      <h3 class="text-lg font-semibold text-red-800">Session Error</h3>
      <p class="text-red-700 mt-1">{{ errorMessage }}</p>
      <div class="mt-3 text-sm text-gray-600">
        <p>Session ID: <span class="font-mono">{{ sessionId }}</span></p>
        <p>Organization ID: <span class="font-mono">{{ organizationId }}</span></p>
      </div>
    </div>
  </div>
</div>

<div *ngIf="!isLoading && !hasError" class="w-full max-w-6xl mx-auto p-6 space-y-8">
  <!-- Header with session info -->
  <div class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
      <div>
        <h2 class="text-2xl font-bold text-gray-900 dark:text-white">
          Kraken Session Monitor (Angular)
        </h2>
        <div class="mt-2 space-y-1">
          <p class="text-gray-600 dark:text-gray-400">
            Session: <span class="font-mono font-semibold">{{ sessionId }}</span>
          </p>
          <p class="text-gray-600 dark:text-gray-400">
            Organization: <span class="font-mono font-semibold">{{ organizationId }}</span>
          </p>
        </div>
      </div>
      
      <div class="flex items-center gap-3">
        <span class="text-sm font-medium text-gray-600">Status:</span>
        <span class="px-4 py-2 rounded-full text-sm font-semibold border" [ngClass]="getStatusColorClass((sessionData$ | async)?.status || '')">
          {{ ((sessionData$ | async)?.status || 'UNKNOWN') | uppercase }}
        </span>
        <div *ngIf="isTyping$ | async" class="flex items-center gap-2 animate-pulse">
          <div class="h-2 w-2 rounded-full bg-green-500"></div>
          <span class="text-sm text-green-600 font-medium">TYPING...</span>
        </div>
      </div>
    </div>
  </div>

  <!-- Current Streaming Delta (Typewriter Effect) -->
  <div class="bg-gradient-to-r from-gray-900 to-gray-800 rounded-xl border border-gray-700 p-6 shadow-lg">
    <div class="flex items-center justify-between mb-4">
      <h3 class="text-lg font-semibold text-gray-100 flex items-center gap-2">
        <span class="h-2 w-2 rounded-full bg-blue-500 animate-pulse"></span>
        LIVE STREAMING (LAST DELTA)
      </h3>
      <span *ngIf="(sessionData$ | async)?.lastDeltaTimestamp" class="text-sm text-gray-400">
        {{ formatTimestamp((sessionData$ | async)?.lastDeltaTimestamp) }}
      </span>
    </div>
    
    <div
      #deltaContainer
      class="min-h-[150px] max-h-[300px] overflow-y-auto bg-black/30 rounded-lg border border-gray-700 p-5 font-mono"
      (scroll)="onScroll($event)"
    >
      <div class="text-gray-100 whitespace-pre-wrap leading-relaxed">
        {{ (typewriterText$ | async) || '' }}
        <span *ngIf="isTyping$ | async" class="inline-block h-5 w-[2px] bg-blue-400 ml-1 animate-pulse align-middle"></span>
      </div>
      
      <div *ngIf="!(sessionData$ | async)?.lastDelta && !(isTyping$ | async)" class="text-gray-500 italic">
        Waiting for streaming response from Kraken...
      </div>
    </div>
    
    <div class="mt-4 flex items-center justify-between text-sm">
      <div class="text-gray-400">
        <span *ngIf="isTyping$ | async" class="flex items-center gap-2">
          <span class="h-1.5 w-1.5 rounded-full bg-green-500 animate-pulse"></span>
          Kraken is thinking...
        </span>
        <span *ngIf="(sessionData$ | async)?.lastDelta && !(isTyping$ | async)" class="text-green-400">✓ Stream complete</span>
      </div>
      <div class="text-gray-500">
        Typewriter speed: {{ typewriterSpeed }}ms/char
      </div>
    </div>
  </div>

  <!-- Accumulated Response with Auto-scroll -->
  <div class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
    <div class="flex items-center justify-between mb-4">
      <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100">
        ACCUMULATED RESPONSE HISTORY
      </h3>
      <div class="flex items-center gap-2 text-sm text-gray-500">
        <span class="h-2 w-2 rounded-full bg-green-500"></span>
        Auto-scroll: {{ accumulatedText.length > 0 ? 'ACTIVE' : 'INACTIVE' }}
      </div>
    </div>
    
    <div
      #accumulatedContainer
      class="min-h-[300px] max-h-[600px] overflow-y-auto bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700 p-5"
      (scroll)="onScroll($event)"
    >
      <div *ngIf="accumulatedText; else noAccumulatedText">
        <pre class="text-gray-800 dark:text-gray-200 whitespace-pre-wrap font-sans leading-relaxed">
          {{ accumulatedText }}
        </pre>
      </div>
      <ng-template #noAccumulatedText>
        <div class="h-full flex items-center justify-center text-gray-500 italic">
          No accumulated response yet. The streaming content will appear here.
        </div>
      </ng-template>
    </div>
    
    <div class="mt-4 flex items-center justify-between text-sm text-gray-500">
      <div>
        Characters: <span class="font-mono font-semibold">{{ accumulatedText.length }}</span>
      </div>
      <div class="flex items-center gap-2">
        <span class="h-2 w-2 rounded-full bg-blue-500"></span>
        Real-time Firestore listener active
      </div>
    </div>
  </div>

  <!-- Blackboard Context (Collapsible) -->
  <div *ngIf="(sessionData$ | async)?.blackboard" class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
    <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-4">
      BLACKBOARD CONTEXT
    </h3>
    <div class="bg-gray-50 dark:bg-gray-900 rounded-lg p-4 max-h-[400px] overflow-y-auto">
      <pre class="text-sm text-gray-700 dark:text-gray-300 whitespace-pre-wrap">
        {{ (sessionData$ | async)?.blackboard | json }}
      </pre>
    </div>
  </div>
</div>

// frontend/components/SessionViewer.tsx
'use client';

import { useEffect, useState, useRef, useCallback } from 'react';
import { doc, onSnapshot, Timestamp } from 'firebase/firestore';
import { db } from '../lib/firebase';

interface SessionViewerProps {
  sessionId?: string;
  organizationId?: string;
  typewriterSpeed?: number;
}

interface SessionData {
  organizationId: string;
  userId: string;
  lastDelta: string;
  lastDeltaTimestamp: Timestamp;
  status: 'active' | 'completed' | 'error';
  blackboard?: {
    [key: string]: any;
  };
}

// Hook para efeito typewriter
const useTypewriter = (text: string, speed: number = 20) => {
  const [displayedText, setDisplayedText] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const timeoutRef = useRef<NodeJS.Timeout>();

  useEffect(() => {
    // Reset when text changes
    setDisplayedText('');
    setIsTyping(true);

    let currentIndex = 0;
    
    const typeNextChar = () => {
      if (currentIndex < text.length) {
        setDisplayedText(prev => prev + text.charAt(currentIndex));
        currentIndex++;
        timeoutRef.current = setTimeout(typeNextChar, speed);
      } else {
        setIsTyping(false);
      }
    };

    // Start typing after a small delay for better UX
    const startDelay = setTimeout(() => {
      typeNextChar();
    }, 100);

    return () => {
      clearTimeout(startDelay);
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
      }
    };
  }, [text, speed]);

  return { displayedText, isTyping };
};

// Hook para scroll automático inteligente
const useAutoScroll = (dependencies: any[]) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const isUserScrolledUp = useRef(false);

  const checkUserScroll = useCallback(() => {
    if (!containerRef.current) return;
    
    const { scrollTop, scrollHeight, clientHeight } = containerRef.current;
    const isAtBottom = scrollHeight - scrollTop - clientHeight < 50;
    isUserScrolledUp.current = !isAtBottom;
  }, []);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    container.addEventListener('scroll', checkUserScroll);
    return () => container.removeEventListener('scroll', checkUserScroll);
  }, [checkUserScroll]);

  useEffect(() => {
    if (!containerRef.current || isUserScrolledUp.current) return;

    // Smooth scroll to bottom
    containerRef.current.scrollTo({
      top: containerRef.current.scrollHeight,
      behavior: 'smooth'
    });
  }, dependencies);

  return containerRef;
};

export default function SessionViewer({
  sessionId = 'test-session-001',
  organizationId = 'org-pablo-astrologia',
  typewriterSpeed = 20,
}: SessionViewerProps) {
  const [sessionData, setSessionData] = useState<SessionData | null>(null);
  const [accumulatedText, setAccumulatedText] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [lastDeltaKey, setLastDeltaKey] = useState(0); // Força re-render do typewriter

  const { displayedText: typedDelta, isTyping } = useTypewriter(
    sessionData?.lastDelta || '',
    typewriterSpeed
  );

  // Ref para scroll automático
  const accumulatedContainerRef = useAutoScroll([accumulatedText]);
  const deltaContainerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!sessionId) return;

    const sessionRef = doc(db, 'sessions', sessionId);
    
    const unsubscribe = onSnapshot(
      sessionRef,
      (snapshot) => {
        if (snapshot.exists()) {
          const data = snapshot.data() as SessionData;
          
          // Validação de organização (multi-tenancy)
          if (data.organizationId !== organizationId) {
            setError(`Session does not belong to organization: ${organizationId}`);
            return;
          }

          setSessionData(data);
          setError(null);

          // Acumular texto imediatamente para evitar race condition
          if (data.lastDelta) {
            setAccumulatedText(prev => {
              // Verifica se o final do texto acumulado já contém o delta para evitar duplicidade
              if (prev.endsWith(data.lastDelta)) return prev;
              return prev + data.lastDelta;
            });
            setLastDeltaKey(prev => prev + 1); // Reinicia o typewriter
          }

          setLoading(false);
        } else {
          setError(`Session "${sessionId}" not found in Firestore`);
          setLoading(false);
        }
      },
      (err) => {
        console.error('Error listening to session:', err);
        setError(`Firestore error: ${err.message}`);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [sessionId, organizationId]);

  // Efeito para scroll automático no lastDelta enquanto digita
  useEffect(() => {
    if (deltaContainerRef.current && isTyping) {
      deltaContainerRef.current.scrollTop = deltaContainerRef.current.scrollHeight;
    }
  }, [typedDelta, isTyping]);

  // Status color mapping
  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'bg-green-100 text-green-800 border-green-300';
      case 'completed': return 'bg-blue-100 text-blue-800 border-blue-300';
      case 'error': return 'bg-red-100 text-red-800 border-red-300';
      default: return 'bg-gray-100 text-gray-800 border-gray-300';
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center p-8 space-y-4">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
        <p className="text-gray-600 dark:text-gray-400">
          Listening to session: <span className="font-mono font-bold">{sessionId}</span>
        </p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-lg p-6">
        <div className="flex items-start gap-3">
          <div className="flex-shrink-0">
            <div className="h-8 w-8 rounded-full bg-red-100 flex items-center justify-center">
              <span className="text-red-600 font-bold">!</span>
            </div>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-red-800">Session Error</h3>
            <p className="text-red-700 mt-1">{error}</p>
            <div className="mt-3 text-sm text-gray-600">
              <p>Session ID: <span className="font-mono">{sessionId}</span></p>
              <p>Organization ID: <span className="font-mono">{organizationId}</span></p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full max-w-6xl mx-auto p-6 space-y-8">
      {/* Header with session info */}
      <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
              Kraken Session Monitor
            </h2>
            <div className="mt-2 space-y-1">
              <p className="text-gray-600 dark:text-gray-400">
                Session: <span className="font-mono font-semibold">{sessionId}</span>
              </p>
              <p className="text-gray-600 dark:text-gray-400">
                Organization: <span className="font-mono font-semibold">{organizationId}</span>
              </p>
            </div>
          </div>
          
          <div className="flex items-center gap-3">
            <span className="text-sm font-medium text-gray-600">Status:</span>
            <span className={`px-4 py-2 rounded-full text-sm font-semibold border ${getStatusColor(sessionData?.status || '')}`}>
              {sessionData?.status?.toUpperCase() || 'UNKNOWN'}
            </span>
            {isTyping && (
              <div className="flex items-center gap-2 animate-pulse">
                <div className="h-2 w-2 rounded-full bg-green-500"></div>
                <span className="text-sm text-green-600 font-medium">TYPING...</span>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Current Streaming Delta (Typewriter Effect) */}
      <div className="bg-gradient-to-r from-gray-900 to-gray-800 rounded-xl border border-gray-700 p-6 shadow-lg">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-semibold text-gray-100 flex items-center gap-2">
            <span className="h-2 w-2 rounded-full bg-blue-500 animate-pulse"></span>
            LIVE STREAMING (LAST DELTA)
          </h3>
          {sessionData?.lastDeltaTimestamp && (
            <span className="text-sm text-gray-400">
              {sessionData.lastDeltaTimestamp.toDate().toLocaleTimeString()}
            </span>
          )}
        </div>
        
        <div
          ref={deltaContainerRef}
          className="min-h-[150px] max-h-[300px] overflow-y-auto bg-black/30 rounded-lg border border-gray-700 p-5 font-mono"
        >
          <div key={lastDeltaKey} className="text-gray-100 whitespace-pre-wrap leading-relaxed">
            {typedDelta}
            {isTyping && (
              <span className="inline-block h-5 w-[2px] bg-blue-400 ml-1 animate-pulse align-middle"></span>
            )}
          </div>
          
          {!sessionData?.lastDelta && !isTyping && (
            <div className="text-gray-500 italic">
              Waiting for streaming response from Kraken...
            </div>
          )}
        </div>
        
        <div className="mt-4 flex items-center justify-between text-sm">
          <div className="text-gray-400">
            {isTyping ? (
              <span className="flex items-center gap-2">
                <span className="h-1.5 w-1.5 rounded-full bg-green-500 animate-pulse"></span>
                Kraken is thinking...
              </span>
            ) : sessionData?.lastDelta ? (
              <span className="text-green-400">✓ Stream complete</span>
            ) : null}
          </div>
          <div className="text-gray-500">
            Typewriter speed: {typewriterSpeed}ms/char
          </div>
        </div>
      </div>

      {/* Accumulated Response with Auto-scroll */}
      <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
            ACCUMULATED RESPONSE HISTORY
          </h3>
          <div className="flex items-center gap-2 text-sm text-gray-500">
            <span className="h-2 w-2 rounded-full bg-green-500"></span>
            Auto-scroll: {accumulatedText.length > 0 ? 'ACTIVE' : 'INACTIVE'}
          </div>
        </div>
        
        <div
          ref={accumulatedContainerRef}
          className="min-h-[300px] max-h-[600px] overflow-y-auto bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700 p-5"
        >
          {accumulatedText ? (
            <pre className="text-gray-800 dark:text-gray-200 whitespace-pre-wrap font-sans leading-relaxed">
              {accumulatedText}
            </pre>
          ) : (
            <div className="h-full flex items-center justify-center text-gray-500 italic">
              No accumulated response yet. The streaming content will appear here.
            </div>
          )}
        </div>
        
        <div className="mt-4 flex items-center justify-between text-sm text-gray-500">
          <div>
            Characters: <span className="font-mono font-semibold">{accumulatedText.length}</span>
          </div>
          <div className="flex items-center gap-2">
            <span className="h-2 w-2 rounded-full bg-blue-500"></span>
            Real-time Firestore listener active
          </div>
        </div>
      </div>

      {/* Blackboard Context (Collapsible) */}
      {sessionData?.blackboard && Object.keys(sessionData.blackboard).length > 0 && (
        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-4">
            BLACKBOARD CONTEXT
          </h3>
          <div className="bg-gray-50 dark:bg-gray-900 rounded-lg p-4 max-h-[400px] overflow-y-auto">
            <pre className="text-sm text-gray-700 dark:text-gray-300 whitespace-pre-wrap">
              {JSON.stringify(sessionData.blackboard, null, 2)}
            </pre>
          </div>
        </div>
      )}
    </div>
  );
}
